branch-defaults:
  master:
    environment: vpager-test
environment-defaults:
  vpager-test:
    branch: null
    repository: null
deploy:
  artifact: vpager-service/target/vpager-service.jar
global:
  application_name: VPager
  default_ec2_keyname: zealcon-bamboo-key
  default_platform: 64bit Amazon Linux 2016.09 v2.4.0 running Java 8
  default_region: us-east-1
  profile: null
  sc: git
